import "./globals.css";

export const metadata = {
  title: "SnapCart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" w-full min-h-screen bg-linear-to-b from-green-100 to-white">
        {children} 
      </body>
    </html>
  );
}
